### ISSUE TITLE
a lot of tmp files in project dir and no completion.

### ISSUE THREAD

**Issue by houssemDevs** [DamnWidget/anaconda_rust#4] opened 2016-05-24 18:20 UTC
Hi I installed anaconda_rust, when I try to tape `use std::io::` I expect some completion but I get nothing except some word from the current file, and a lot of tmp files are created in the project dir.

I am on windows 10, rust nightly 1.10, mingw gcc 5.3.0, python 3 and python 2.

**Comment by DamnWidget** [comment] 2016-05-24 18:32
Probably the racer process is crashing, take a look at your anaconda log files in `%APPDATA%\\Jedi\\Jedi\\<project_name>\\anaconda_server.log`

**Comment by houssemDevs** [comment] 2016-05-24 18:47
this is the content of the log file: [patebin](http://pastebin.com/cqYYPusV)

I tried to understand something but no chance :(

**Comment by DamnWidget** [comment] 2016-05-24 18:57
This seems to be a duplicate of #3 and be related with https://github.com/phildawes/racer/issues/546, I'll close this issue, continue the discussion in #3 please

**Closed as completed by DamnWidget** 2016-05-24 18:57 UTC

**Comment by houssemDevs** [comment] 2016-05-24 19:05
OK i will thank you
