### ISSUE TITLE
Autocompletion fails when non-ASCII characters are present

### ISSUE THREAD

**Issue by Philipp91** [DamnWidget/anaconda_rust#24] opened 2017-01-27 15:44 UTC
1. Start a new rust binary with the usual code in it:
```
fn main() {
    println!("Hello, world!");
}
```

2. Check that autocompletion works by typing `use std::convert::` somewhere. It will recommend stuff like `AsRef` and `Into`.

3. Change the output string to `"Hällo wörld"` (or sth like that).

4. Again try autocompletion by typing `use std::convert::`, which is now broken. It only recommends stuff from the file itself (`fn`, `main`, `Hällo`, ...).

Output in `anaconda_jsonserver.log`:
```
2017-01-27 16:25:16,319: INFO    : client requests: autocomplete
2017-01-27 16:25:16,328: ERROR   : The underlying racer tool raised an exception
2017-01-27 16:25:16,328: ERROR   : 'ascii' codec can't encode character u'\xe4' in position 47: ordinal not in range(128)
2017-01-27 16:25:16,329: DEBUG   : Traceback (most recent call last):
  File "/home/rustcrypto/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/../../../anaconda_rust/plugin/handlers_rust/commands/autocomplete.py", line 36, in run
    'completions': self.completions(),
  File "/home/rustcrypto/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/../../../anaconda_rust/plugin/handlers_rust/commands/autocomplete.py", line 89, in completions
    output, error = racer.communicate(src)
  File "/usr/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1417, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1481, in _communicate_with_poll
    input_offset += os.write(fd, chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 47: ordinal not in range(128)
```

Calling `racer` with the same file from disk manually works fine. So the problem seems to be that anaconda_rust cannot write out the non-ASCII character through the pipe.

If possible, please tell me whether or not you can fix this by next week (if not, I would have to modify some files of mine as a workaround). It's not urgent, I just need to know.

**Comment by DamnWidget** [comment] 2017-01-27 15:54
Thanks for reporting this, I will fix it in some hours.

**Comment by Philipp91** [comment] 2017-01-27 16:02
It works when I change this line https://github.com/DamnWidget/anaconda_rust/blob/master/plugin/handlers_rust/commands/autocomplete.py#L85 to `src = self.settings['source'].encode('utf8')` (I have Python 2.7).

**Comment by DamnWidget** [comment] 2017-01-27 16:06
Can you open your ST3 console and tell me what the following line of code prints out when you copy and paste it into the console?

```python
import sys; print(sys.stdin.encoding);
```

**Comment by Philipp91** [comment] 2017-01-27 16:07
`UTF-8`

Ubuntu 16.04, latest Sublime version.

**Comment by DamnWidget** [comment] 2017-01-27 16:15
I can not reproduce it myself, so I need some assistance.

Can you change line 89 to this and try again?
```python
try:
    output, error = racer.communicate(src)
except UnicodeEncodeError:
    output, error = racer.communicate(src.decode('utf8').encode('utf8'))
```

**Comment by Philipp91** [comment] 2017-01-27 16:24
```
2017-01-27 17:20:46,322: DEBUG   : Traceback (most recent call last):
  File "/home/rustcrypto/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/../../../anaconda_rust/plugin/handlers_rust/commands/autocomplete.py", line 36, in run
    'completions': self.completions(),
  File "/home/rustcrypto/.config/sublime-text-3/Packages/Anaconda/anaconda_server/lib/../../../anaconda_rust/plugin/handlers_rust/commands/autocomplete.py", line 92, in completions
    output, error = racer.communicate(src.decode('utf8').encode('utf8'))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 48: ordinal not in range(128)
```

Removed the `.encode('utf8')` and it works again.

(Note that my line 85 is back in the original state: `src = self.settings['source']`)

**Comment by DamnWidget** [comment] 2017-01-27 16:30
I really hate these unicode problems in Python < 3, I do not understand why your buffer is not rightly encoded already.

```output, error = racer.communicate(src.decode('utf8'))``` works for you then, right?

P.S: the problem in your case is that a bytes string rightly encoded has been `decoded` again converting it into a `unicode` string and then has been tried to be decoded again by the stdin write operation.

**Comment by Philipp91** [comment] 2017-01-27 16:33
No, almost:

```
        try:
            output, error = racer.communicate(src)
        except UnicodeEncodeError:
            output, error = racer.communicate(src.encode('utf8'))
```

**Comment by DamnWidget** [comment] 2017-01-27 16:36
Yeah, sorry, I meant `encode` and not `decode` I just deleted the wrong one :D, the problem is that the string is an already rightly encoded bytes string decoded into an unicode string, with the encode you are converting it back to a bytes string

**Comment by Philipp91** [comment] 2017-01-27 16:38
I am not a Python coder nor a Sublime expert.

In other programming languages, the solution is to go all UTF-8, no matter what. From the Python documentation, I gather that Python 2.7 encodings default to ASCII, wheraes Python 3 defaults to UTF-8. So `.encode()` means something different.

I can't test it anywhere else, but to me it seems that changing lines 85-87 to simply `src = self.settings['source'].encode('utf8')` should work everywhere:

- It works on my Python 2.7 installation -- that's what where testing all the time.
- It is equivalent to the line-87-call, because on Python 3.x the encoding defaults to utf8 anyway.

Similarly, I'd take out the `if sys.version_info` from the output part, too. Assuming that Python 2.7 also reads something unicode-y and has to decode it. Though it's not that critical there, because the output is almost always ASCII anyway.

Again: Not sure this would actually work (on Python 3, on Windows, etc.)

**Comment by DamnWidget** [comment] 2017-01-27 16:43
If we change line 85 to that, any well formatted string (sequence of bytes with a encoding) will fail with the opposite error, something like:
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)```

In Python3 we encode the string because we need to convert it explicitly to a sequence of bytes as I/O is gonna be performed by the subprocess module.

**Comment by Philipp91** [comment] 2017-01-27 16:45
Why would an `.encode()` call fail with a `UnicodeDecodeError`?

This is the code that works for me, not sure how many other switches are needed to accomodate other systems:
```
src = self.settings['source'].encode('utf8')
output, error = racer.communicate(src)
output = output.decode('utf8')
error = error.decode('utf8')
```

(And if I understand Python correctly, this code is equivalent to what Python 3 executes with the current code in the repo. The only question is if there are any other <3.x installations that break because the encoding/decoding now newly happens for them.)

**Comment by DamnWidget** [comment] 2017-01-27 17:20
First you have to understand how Python 2 and Python 3 treat a string and what a string means in each of the versions cos is not the same.

In Python 2 a string is just a sequence of bytes, that is why there is a separate object `unicode` that is a sequence of bytes with an specific encoding. In Python 3 all the strings are encoded in 'utf8' and the `unicode` object does not exits, in Python 3 a string and a sequence of bytes are *not* the same thing.

In your case, ST3 get the (to use your own example) `Hällo wörld` from the buffer and passes it to it's embedded Python 3 interpreter as an string object, then, anaconda needs to convert it to a sequence of bytes (as a socket does not know how to process a string object but bytes) with utf8 encode, then that string is converted to the object `b'H\xc3\xa4llo w\xc3\xb6rld'` that is a right bytes sequence in valid UTF8 encoding, then that is sent and process by the anaconda server that could be running under other Python version, as is in your own case.

For whatever reason that sequence of bytes is being converted to the `unicode` object `u'H\xe4llo w\xf6rld'` that is an invalid sequence of bytes with a non valid UTF8 encoding and that is being passed to `Popen.communicate` and that is why you get the `UnicodeEncodeError` that object should be a `str` and not a `unicode` that is why using `encode('utf8')` works in your case, because is converting it into a `str` object with the right encode.

This has to be related with your system encoding configuration. Take a look to the `sys.stdin.encoding` in your default python interpreter.

I did some tests with different interpreters and configurations and seems like is safe enough to always encode the string so I will release a fix for this in some minutes, (doc and goto where also failing).

**Closed as completed** 2017-01-27 20:56 UTC

**Comment by Philipp91** [comment] 2017-01-27 22:40
`sys.stdin.encoding` is `UTF-8` in both Python 2.7.12 and 3.5.2.

Thanks a lot for the fix! I can confirm that the problem is gone in the latest release.

**Comment by DamnWidget** [comment] 2017-01-27 22:57
No problem, thank you for getting involved.
